
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: guestready
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # web:
  #   build:
  #     context: ..
  #     dockerfile: deploy/Dockerfile
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DB_NAME=guestready
  #     - DB_USER=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #   depends_on:
  #     - db
  #   volumes:
  #     - ../:/app

volumes:
  postgres_data:
